provider1:
  hostname: provider1
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: core

provider2:
  hostname: provider2
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: core

provider3:
  hostname: provider3
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: core

provider4:
  hostname: provider4
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: core

provider5:
  hostname: provider5
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: core

dc1dcgw1:
  hostname: dc1dcgw1
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: dcgw

dc1dcgw2:
  hostname: dc1dcgw2
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: dcgw

dc2dcgw1:
  hostname: dc2dcgw1
  platform: sros
  groups:
  - sros
  data:
    site: wan1
    role: dcgw

spine1dc1:
  hostname: spine1dc1
  platform: srlinux
  groups:
  - srl
  data:
    site: dc1
    role: spine

spine2dc1:
  hostname: spine2dc1
  platform: srlinux
  groups:
  - srl
  data:
    site: dc1
    role: spine

spine1dc2:
  hostname: spine1dc2
  platform: srlinux
  groups:
  - srl
  data:
    site: dc2
    role: spine

leaf1dc1:
  hostname: leaf1dc1
  platform: srlinux
  groups:
  - srl
  data:
    site: dc1
    role: leaf

leaf2dc1:
  hostname: leaf2dc1
  platform: srlinux
  groups:
  - srl
  data:
    site: dc1
    role: leaf

leaf3dc1:
  hostname: leaf3dc1
  platform: srlinux
  groups:
  - srl
  data:
    site: dc1
    role: leaf

leaf4dc1:
  hostname: leaf4dc1
  platform: srlinux
  groups:
  - srl
  data:
    site: dc1
    role: leaf

leaf1dc2:
  hostname: leaf1dc2
  platform: srlinux
  groups:
  - srl
  data:
    site: dc2
    role: leaf

leaf2dc2:
  hostname: leaf2dc2
  platform: srlinux
  groups:
  - srl
  data:
    site: dc2
    role: leaf
