---
inventory:
    plugin: YAMLInventory
    options:
        host_file: "/nornir/hosts.yaml"
        group_file: "/nornir/groups.yaml"
        defaults_file: "/nornir/defaults.yaml"
runner:
    # plugin: serial
    plugin: threaded
    options:
        num_workers: 40
user_defined:
    intent_dir: "./intent"
