---
inventory:
    plugin: YAMLInventory
    options:
        host_file: "/home/samuelbarata/labs/dci-netprism-labnornir/nornir/hosts.yaml"
        group_file: "/home/samuelbarata/labs/dci-netprism-labnornir/nornir/groups.yaml"
        defaults_file: "/home/samuelbarata/labs/dci-netprism-labnornir/nornir/defaults.yaml"
runner:
    # plugin: serial
    plugin: runner
        plugin: threaded
        option":
            num_workers: 20
user_defined:
    intent_dir: "./intent"
